# Generated by Django 2.0 on 2018-01-11 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180110_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='team',
            name='description',
            field=models.TextField(help_text='enter name(s) of your team.'),
        ),
    ]
