# Generated by Django 2.0 on 2018-01-11 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180111_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='minteamsize',
            field=models.IntegerField(default=1),
        ),
    ]
